services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teleconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    image: tekeconnect_backend:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tekeconnect_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/teleconnect
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend_network

  ui:
    image: tekeconnect_ui:1.0.0
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "3000:3000"
    networks:
      - frontend_network

networks:
  backend_network:
  frontend_network:

volumes:
  postgres_data:
