openapi: 3.0.1
info:
  title: Authentication API
  description: API for user authentication
  version: 1.0.0
tags:
  - name: auth
    description: API to handle user authentication
paths:
  /auth/signup:
    post:
      summary: Register a new user
      operationId: registerUser
      tags:
        - auth
      requestBody:
        description: User registration details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request, invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  /auth/login:
    post:
      summary: Authenticate a user
      operationId: loginUser
      tags:
        - auth
      requestBody:
        description: User login credentials, login can be email or phone number
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Unauthorized, invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  /auth/refresh-token:
    post:
      summary: Refresh JWT token
      operationId: refreshToken
      tags:
        - auth
      requestBody:
        description: Request to refresh JWT token
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
      responses:
        '200':
          description: New JWT token generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '403':
          description: Forbidden, invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
  /auth/logout:
    post:
      summary: Logout a user
      operationId: logoutUser
      tags:
        - auth
      requestBody:
        description: Request to logout user by invalidating the token
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '204':
          description: User logged out successfully, token invalidated
        '400':
          description: Bad request, invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
components:
  schemas:
    RegisterUserRequest:
      type: object
      properties:
        phoneNumber:
          type: string
          example: "1234567890"
        password:
          type: string
          format: password
        email:
          type: string
          format: email
        name:
          type: string
          example: "John"
        surname:
          type: string
          example: "Doe"
      required:
        - phoneNumber
        - password
        - email
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          example: "1234567890 or john.doe@example.com"
        password:
          type: string
          format: password
      required:
        - username
        - password
    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        refreshToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        userId:
          type: integer
          example: 1
        role:
          type: string
          example: "ROLE_USER"
      required:
        - token
        - refreshToken
        - userId
        - role
    TokenRefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
          example: "dGhpc2lzbXlyZWZyZXNodG9rZW4="
      required:
        - refreshToken
    TokenRequest:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        refreshToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      required:
        - token
        - refreshToken
    AuthError:
      type: object
      properties:
        error:
          type: string
          example: "Invalid or missing token"
