openapi: 3.0.1
info:
  title: TeleConnect Manager API
  description: API for managing tariffs in the TeleConnect Manager application
  version: 1.0.0
tags:
  - name: tariff
    description: API to interact with tariffs
paths:
  /tariff:
    post:
      summary: Create a new tariff
      operationId: createTariff
      tags:
        - tariff
      security:
        - bearerAuth: [ ]
      requestBody:
        description: Tariff to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TariffDTO'
      responses:
        '201':
          description: Tariff created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffDTO'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    put:
      summary: Update a tariff
      operationId: updateTariff
      tags:
        - tariff
      security:
        - bearerAuth: [ ]
      requestBody:
        description: Tariff to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TariffDTO'
      responses:
        '200':
          description: Tariff updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffDTO'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    get:
      summary: Get all tariffs with pagination
      operationId: getAllTariffs
      tags:
        - tariff
      security:
        - bearerAuth: [ ]
      parameters:
        - name: priceMin
          in: query
          required: false
          schema:
            type: number
            format: double
        - name: priceMax
          in: query
          required: false
          schema:
            type: number
            format: double
        - name: dataLimitMin
          in: query
          required: false
          schema:
            type: integer
        - name: dataLimitMax
          in: query
          required: false
          schema:
            type: integer
        - name: callMinutesMin
          in: query
          required: false
          schema:
            type: integer
        - name: callMinutesMax
          in: query
          required: false
          schema:
            type: integer
        - name: smsLimitMin
          in: query
          required: false
          schema:
            type: integer
        - name: smsLimitMax
          in: query
          required: false
          schema:
            type: integer
        - name: isActive
          in: query
          required: false
          schema:
            type: boolean
        - name: isUsed
          in: query
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Number of items to return per page (default is 25)
          example: 25
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: The page number to start with (default is 0)
          example: 0
      responses:
        '200':
          description: A paginated list of tariffs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTariffResponse'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
  /tariff/{id}:
    get:
      summary: Get a tariff by ID
      operationId: getTariffById
      tags:
        - tariff
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tariff details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffDTO'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '404':
          description: Tariff not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    delete:
      summary: Delete a tariff
      operationId: deleteTariff
      tags:
        - tariff
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tariff deleted
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '404':
          description: Tariff not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
  /tariff/user/{userId}:
    get:
      summary: Get a tariff by user ID
      operationId: getTariffByUserId
      tags:
        - tariff
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tariff details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffDTO'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '404':
          description: Tariff not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
components:
  schemas:
    TariffDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: double
        dataLimit:
          type: integer
        callMinutes:
          type: integer
        smsLimit:
          type: integer
        description:
          type: string
        isActive:
          type: boolean
        isUsed:
          type: boolean
      required:
        - name
        - price
        - description
    PaginatedTariffResponse:
      type: object
      properties:
        tariffs:
          type: array
          items:
            $ref: '#/components/schemas/TariffDTO'
        totalItems:
          type: integer
        totalPages:
          type: integer
        currentPage:
          type: integer
        itemsOnPage:
          type: integer
    AuthError:
      type: object
      properties:
        error:
          type: string
          example: "Invalid or missing token"
    ForbiddenError:
      type: object
      properties:
        error:
          type: string
          example: "Forbidden: insufficient permissions"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
