openapi: 3.0.1
info:
  title: User Management API
  description: API for managing users in the User Management application
  version: 1.0.0
tags:
  - name: user
    description: API to interact with users
paths:
  /users:
    get:
      summary: Get all users with pagination
      operationId: getAllUsers
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - name: phoneNumber
          in: query
          required: false
          schema:
            type: string
        - name: email
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: surname
          in: query
          required: false
          schema:
            type: string
        - name: role
          in: query
          required: false
          schema:
            type: string
        - name: tariffId
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 25
          description: Number of users to return per page (default is 25)
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: Number of pages to skip (default is 0)
      responses:
        '200':
          description: A paginated list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserResponse'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - user
      security:
        - bearerAuth: [ ]
      requestBody:
        description: User to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    put:
      summary: Update a user
      operationId: updateUser
      tags:
        - user
      security:
        - bearerAuth: [ ]
      requestBody:
        description: User to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '404':
          description: User not found
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    delete:
      summary: Delete a user
      operationId: deleteUser
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
components:
  schemas:
    PaginatedUserResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserDto'
        pagination:
          type: object
          properties:
            currentPage:
              type: integer
              example: 1
            totalPages:
              type: integer
              example: 10
            totalItems:
              type: integer
              example: 100
            itemsOnPage:
              type: integer
              example: 25
    UserDto:
      type: object
      properties:
        id:
          type: integer
        phoneNumber:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
        email:
          type: string
          nullable: false
        name:
          type: string
        surname:
          type: string
        role:
          type: string
        tariffId:
          type: integer
        tariff_adjustment_id:
          type: integer
        birthDate:
          type: string
          format: date
      required:
        - phoneNumber
        - password
        - email
        - name
        - surname
        - role
    AuthError:
      type: object
      properties:
        error:
          type: string
          example: "Invalid or missing token"
    ForbiddenError:
      type: object
      properties:
        error:
          type: string
          example: "Forbidden: insufficient permissions"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
