openapi: 3.0.1
info:
  title: User Management API
  description: API for managing users in the User Management application
  version: 1.0.0
tags:
  - name: user
    description: API to interact with users
paths:
  /users:
    get:
      summary: Get all users
      operationId: getAllUsers
      tags:
        - user
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - user
      security:
        - bearerAuth: [ ]
      requestBody:
        description: User to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    put:
      summary: Update a user
      operationId: updateUser
      tags:
        - user
      security:
        - bearerAuth: [ ]
      requestBody:
        description: User to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '404':
          description: User not found
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    delete:
      summary: Delete a user
      operationId: deleteUser
      tags:
        - user
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: integer
        phoneNumber:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
        email:
          type: string
          nullable: false
        name:
          type: string
        surname:
          type: string
        role:
          type: string
        tariffId:
          type: integer
      required:
        - phoneNumber
        - password
        - email
        - name
        - surname
        - role
    AuthError:
      type: object
      properties:
        error:
          type: string
          example: "Invalid or missing token"
    ForbiddenError:
      type: object
      properties:
        error:
          type: string
          example: "Forbidden: insufficient permissions"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
