spring:
  application:
    name: teleconnect
  datasource:
    url: jdbc:postgresql://localhost:5432/teleconnect
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
