spring:
  application:
    name: teleconnect
  datasource:
    url: jdbc:postgresql://localhost:5432/teleconnect
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b # it's just a pet project, don't worry
    expiration-time: 3600000
