spring:
  application:
    name: teleconnect
  datasource:
    url: jdbc:postgresql://localhost:5432/teleconnect
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: teleconnect344@gmail.com
    password: "brgv mnia rpzd suhe"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b # it's just a pet project, don't worry
    refresh-secret-key: c2f20c5a2296d4fa83b1a9a1234b9a56d6f4b5a9e1f42c9a48c2e4f6b8a7e2a1b2c3d4e5f6789a0b1c2d3e4f5a6b7c8d9e0f1234567890abcdef1234567890abcdef
    reset-password-secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 36000000
    refresh-expiration-time: 86400000
    reset-password-expiration-time: 360000

document:
  filePath: src/main/resources/static/documents