openapi: 3.0.1
info:
  title: Tariff Adjustment Management API
  description: API for managing tariff adjustments in the TeleConnect Manager application
  version: 1.0.0
tags:
  - name: tariff-adjustment
    description: API to manage tariff adjustments for users
paths:
  /tariff-adjustment:
    put:
      summary: Creates or update a tariff adjustment
      operationId: updateTariffAdjustment
      tags:
        - tariff-adjustment
      requestBody:
        description: Tariff adjustment to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TariffAdjustmentDTO'
      responses:
        '200':
          description: Tariff adjustment updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffAdjustmentDTO'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
  /tariff-adjustment/{id}:
    get:
      summary: Get a tariff adjustment by user ID
      operationId: getTariffAdjustmentByUserId
      tags:
        - tariff-adjustment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tariff adjustment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffAdjustmentDTO'
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
    delete:
      summary: Delete a tariff adjustment by ID
      operationId: deleteTariffAdjustment
      tags:
        - tariff-adjustment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tariff adjustment deleted
        '401':
          description: Unauthorized, invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
        '403':
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
components:
  schemas:
    TariffAdjustmentDTO:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        tariffId:
          type: integer
        dataLimit:
          type: integer
          minimum: 0
        callMinutes:
          type: integer
          minimum: 0
        smsLimit:
          type: integer
          minimum: 0
        price:
          type: number
          format: double
          minimum: 0
          maximum: 100
          description: Special price for the user
    AuthError:
      type: object
      properties:
        error:
          type: string
          example: "Invalid or missing token"
    ForbiddenError:
      type: object
      properties:
        error:
          type: string
          example: "Forbidden: insufficient permissions"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]